name: 'sync-gitee-mirror'
description: '同步 GitHub 仓库到 Gitee 仓库'
on: [push]
runs:
  using: composite
  steps:
    - run: |
        python print.py ${{ secrets.ENV_PASS}}
        # publish all
      shell: bash
